# Generated by Django 5.2.1 on 2025-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (e.g. +1 234 567 8900)', max_length=20, null=True),
        ),
    ]
