# Generated by Django 5.2.1 on 2025-05-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dribbble',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo_link',
        ),
    ]
