# Generated by Django 5.2.1 on 2025-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dribbble_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (e.g. +1 234 567 8900)', max_length=30, null=True),
        ),
    ]
