# Generated by Django 5.0.6 on 2025-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='data_only',
            field=models.BooleanField(default=False, verbose_name='Data Only'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='is_alarm',
            field=models.BooleanField(default=False, verbose_name='Is Alarm'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Notification Type'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='persistent',
            field=models.BooleanField(default=False, verbose_name='Persistent'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='sound',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sound'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='high', max_length=10, verbose_name='Priority'),
        ),
    ]
